---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	plan(plan)
	search(search)
	evaluate(evaluate)
	synthesise(synthesise)
	error(error)
	__end__([<p>__end__</p>]):::last
	__start__ --> plan;
	evaluate -.-> error;
	evaluate -.-> search;
	evaluate -.-> synthesise;
	plan -.-> error;
	plan -.-> search;
	search -.-> error;
	search -.-> evaluate;
	synthesise -.-> __end__;
	synthesise -.-> error;
	error --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
